name: Run TestNG Tests

# Trigger workflow on push or pull request
on:
  push:
    branches:
      - main
  workflow_dispatch:   # 👈 this enables "Run workflow" button

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up JDK (Java)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # Step 3: Cache Maven dependencies (optional, speeds up builds)
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Run Maven tests (TestNG through pom.xml)
    - name: Run TestNG tests
      run: mvn clean test
